version: "3.3"

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    restart: on-failure
    networks:
      standard-network:
        aliases:
          - elasticsearch
    volumes:
      - /mnt/samba/projects/lifeline/elasticsearch-data:/usr/share/elasticsearch/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      standard-network:
        aliases:
          - grafana
    volumes:
      - /mnt/samba/projects/lifeline/grafana-data:/var/lib/grafana

networks:
  standard-network:
